/**
 * Markdown Formatter Types
 * 
 * Type definitions for Markdown output format.
 */

export interface MarkdownOptions {
  /** Report title */
  title?: string;
  /** Include summary table */
  includeSummary?: boolean;
  /** Include file sections */
  includeFiles?: boolean;
  /** Include suggestions */
  includeSuggestions?: boolean;
  /** Use collapsible sections for findings */
  collapsible?: boolean;
  /** Maximum findings to show per file */
  maxFindingsPerFile?: number;
  /** Maximum total findings to show */
  maxFindings?: number;
  /** Include footer */
  includeFooter?: boolean;
  /** Footer text */
  footerText?: string;
  /** Use emoji icons */
  useEmoji?: boolean;
  /** Link to full report */
  reportLink?: string;
}

export const DEFAULT_MARKDOWN_OPTIONS: MarkdownOptions = {
  title: 'VibeCheck Security Scan Results',
  includeSummary: true,
  includeFiles: true,
  includeSuggestions: true,
  collapsible: true,
  maxFindingsPerFile: 10,
  maxFindings: 50,
  includeFooter: true,
  footerText: 'Generated by VibeCheck',
  useEmoji: true,
};

export interface SeverityConfig {
  icon: string;
  label: string;
  color: string;
}

export const SEVERITY_CONFIG: Record<string, SeverityConfig> = {
  error: { icon: '🔴', label: 'Error', color: 'red' },
  warning: { icon: '🟡', label: 'Warning', color: 'yellow' },
  info: { icon: '🔵', label: 'Info', color: 'blue' },
};
