// src/cli/commands/hooks.ts

import { Command } from 'commander';
import * as fs from 'fs/promises';
import * as path from 'path';
import { execSync } from 'child_process';

export const hooksCommand = new Command('hooks')
  .description('Manage Git hooks for VibeCheck')
  .addCommand(
    new Command('install')
      .description('Install pre-commit hook')
      .option('--force', 'Overwrite existing hook')
      .option('--fail-on <severity>', 'Fail commit on severity', 'high')
      .action(installHook)
  )
  .addCommand(
    new Command('uninstall')
      .description('Remove pre-commit hook')
      .action(uninstallHook)
  );

async function installHook(options: { force?: boolean; failOn: string }): Promise<void> {
  const gitRoot = findGitRoot();
  if (!gitRoot) {
    console.error('❌ Not a git repository');
    process.exit(1);
  }

  const hooksDir = path.join(gitRoot, '.git', 'hooks');
  const preCommitPath = path.join(hooksDir, 'pre-commit');

  const exists = await fileExists(preCommitPath);
  if (exists && !options.force) {
    const content = await fs.readFile(preCommitPath, 'utf-8');
    if (!content.includes('vibecheck')) {
      console.error('❌ Pre-commit hook already exists. Use --force to append VibeCheck.');
      process.exit(1);
    }
  }

  const hookScript = generateHookScript(options.failOn);

  if (exists && !options.force) {
    const existing = await fs.readFile(preCommitPath, 'utf-8');
    if (!existing.includes('vibecheck')) {
      await fs.writeFile(preCommitPath, existing + '\n' + hookScript);
    }
  } else {
    await fs.writeFile(preCommitPath, hookScript);
  }

  await fs.chmod(preCommitPath, 0o755);

  console.log('✅ Pre-commit hook installed');
  console.log(`   Fail on: ${options.failOn} severity or above`);

  const huskyDir = path.join(gitRoot, '.husky');
  if (await fileExists(huskyDir)) {
    await installHuskyHook(huskyDir, options.failOn);
  }
}

async function uninstallHook(): Promise<void> {
  const gitRoot = findGitRoot();
  if (!gitRoot) {
    console.error('❌ Not a git repository');
    process.exit(1);
  }

  const preCommitPath = path.join(gitRoot, '.git', 'hooks', 'pre-commit');

  if (await fileExists(preCommitPath)) {
    const content = await fs.readFile(preCommitPath, 'utf-8');

    if (content.includes('# VIBECHECK START')) {
      const cleaned = content.replace(
        /# VIBECHECK START[\s\S]*?# VIBECHECK END\n?/g,
        ''
      );

      if (cleaned.trim() === '#!/bin/sh' || cleaned.trim() === '') {
        await fs.unlink(preCommitPath);
      } else {
        await fs.writeFile(preCommitPath, cleaned);
      }

      console.log('✅ VibeCheck pre-commit hook removed');
    } else {
      console.log('ℹ️  No VibeCheck hook found');
    }
  }
}

function generateHookScript(failOn: string): string {
  return `#!/bin/sh
# VIBECHECK START
# Mock/Fake Data Detection Pre-Commit Hook
# Generated by VibeCheck

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|js|jsx)$' | grep -v -E '\\.(test|spec)\\.(ts|tsx|js|jsx)$' | grep -v '__tests__' | grep -v '__mocks__')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

echo "🔍 VibeCheck: Scanning staged files for mock/fake data..."

TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

for FILE in $STAGED_FILES; do
  if [ -f "$FILE" ]; then
    mkdir -p "$TEMP_DIR/$(dirname $FILE)"
    git show ":$FILE" > "$TEMP_DIR/$FILE" 2>/dev/null || cp "$FILE" "$TEMP_DIR/$FILE"
  fi
done

npx vibecheck scan:mocks --dir "$TEMP_DIR" --fail-on ${failOn} --format text

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "❌ VibeCheck found mock/fake data issues"
  echo ""
  echo "Options:"
  echo "  1. Fix the issues and re-commit"
  echo "  2. Add // vibecheck-disable-next-line <rule-id> to suppress"
  echo "  3. Use --no-verify to bypass (not recommended)"
  echo ""
  exit 1
fi

echo "✅ VibeCheck: No blocking issues found"
# VIBECHECK END
`;
}

async function installHuskyHook(huskyDir: string, failOn: string): Promise<void> {
  const hookPath = path.join(huskyDir, 'pre-commit');

  const huskyScript = `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# VibeCheck Mock Detector
npx vibecheck scan:mocks --staged --fail-on ${failOn}
`;

  const exists = await fileExists(hookPath);
  if (exists) {
    const content = await fs.readFile(hookPath, 'utf-8');
    if (!content.includes('vibecheck')) {
      await fs.appendFile(hookPath, '\n' + huskyScript.split('\n').slice(2).join('\n'));
    }
  } else {
    await fs.writeFile(hookPath, huskyScript);
    await fs.chmod(hookPath, 0o755);
  }

  console.log('✅ Husky pre-commit hook updated');
}

function findGitRoot(): string | null {
  try {
    return execSync('git rev-parse --show-toplevel', { encoding: 'utf-8' }).trim();
  } catch {
    return null;
  }
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
