/**
 * HTML Report Type Definitions
 */

// ============================================================================
// Report Types
// ============================================================================

export interface HtmlReportOptions {
  /** Report title */
  title?: string;
  /** Project name */
  projectName?: string;
  /** Author/generator */
  author?: string;
  /** Theme */
  theme?: 'dark' | 'light';
  /** Include summary section */
  includeSummary?: boolean;
  /** Include charts */
  includeCharts?: boolean;
  /** Include code snippets */
  includeCodeSnippets?: boolean;
  /** Include recommendations */
  includeRecommendations?: boolean;
  /** Group findings by */
  groupBy?: 'file' | 'severity' | 'type' | 'none';
  /** Custom CSS to inject */
  customCss?: string;
  /** Custom footer text */
  footerText?: string;
}

export interface ReportData {
  /** Project information */
  project: ProjectInfo;
  /** Scan results summary */
  summary: ScanSummary;
  /** All findings */
  findings: ReportFinding[];
  /** Timestamp */
  generatedAt: string;
}

export interface ProjectInfo {
  name: string;
  path?: string;
  branch?: string;
  commit?: string;
}

export interface ScanSummary {
  /** Total findings */
  totalFindings: number;
  /** Findings by severity */
  bySeverity: {
    critical: number;
    high: number;
    medium: number;
    low: number;
    info: number;
  };
  /** Findings by type/engine */
  byType: Record<string, number>;
  /** Files scanned */
  filesScanned: number;
  /** Scan duration */
  durationMs: number;
  /** Overall verdict */
  verdict: 'pass' | 'warn' | 'fail';
  /** Security score (0-100) */
  securityScore: number;
}

export interface ReportFinding {
  /** Unique ID */
  id: string;
  /** Finding type/rule */
  type: string;
  /** Severity level */
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  /** Title/message */
  title: string;
  /** Description */
  description?: string;
  /** File path */
  file: string;
  /** Line number */
  line?: number;
  /** Column number */
  column?: number;
  /** Code snippet */
  codeSnippet?: string;
  /** Suggestion for fix */
  suggestion?: string;
  /** Whether auto-fixable */
  autoFixable: boolean;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// Template Types
// ============================================================================

export interface TemplateContext {
  options: Required<HtmlReportOptions>;
  data: ReportData;
  styles: string;
  scripts: string;
}

// ============================================================================
// Constants
// ============================================================================

export const DEFAULT_REPORT_OPTIONS: Required<HtmlReportOptions> = {
  title: 'VibeCheck Security Report',
  projectName: 'Project',
  author: 'VibeCheck',
  theme: 'dark',
  includeSummary: true,
  includeCharts: true,
  includeCodeSnippets: true,
  includeRecommendations: true,
  groupBy: 'severity',
  customCss: '',
  footerText: 'Generated by VibeCheck',
};

export const SEVERITY_COLORS = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#ca8a04',
  low: '#65a30d',
  info: '#0284c7',
} as const;

export const SEVERITY_ICONS = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🟢',
  info: '🔵',
} as const;
